#!/bin/bash

# SSH into our EC2 instance using the environment variables sourced from "env" file
# Using heredoc syntax to send apt commands to install and start nginx
ssh -i $SSHKEY -T $USER@$IPADDR << EOF
sudo apt update
sudo apt install -y nginx
sudo systemctl enable --now nginx
EOF
